### PR TITLE
Use Github Actions to push GHCR on new tag

### PR DESCRIPTION
**Pull request by mbarrien**
Adds a Github Action to build and push Docker images to Github Container Registry (GHCR). This replaces the current use of Docker Hub. This removes our last use of Docker Hub, and leaves the resulting image publicly available, as it is right now.

While here, upgrades the version of Chamber to the latest.

This is alternate to #2; only merge one or the other.

### CODE REVIEW

**Review by atolopko-czi — COMMENTED** [review]
I see there are "dueling" PRs , [one for using ECR](https://github.com/chanzuckerberg/datadog-management/pull/2/files) and this one for GHCR.  KGE is using ECR for all it's Docker images. Is there a preference or use case for using use GHCR?

**Comment by mbarrien** [comment]
The current Docker Hub image is public. Moving to ECR will inherently make it private, even though this Github repo is public. GHCR is our current preferred place for public Docker Image repos that can be downloaded by the public without credentials. I don't know if you had a desire to keep the image public.

**Comment by qorpus** [comment]
I love how I still get all the updates on these repos :D -- Hello chaps :)

**Comment by mbarrien** [comment]
Per discussion in other PR and out-of-band, closing this one in favor of #2.

**Pull request closed without merging**
